language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8-dev'

install:
  - pip install colorama flake8 flake8-bugbear

script:
  - flake8
  - python test_crayons.py
  - python setup.py install
